"""user table

Revision ID: d765ca1f3cfb
Revises: a9503216ab8d
Create Date: 2019-09-14 20:58:00.793648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd765ca1f3cfb'
down_revision = 'a9503216ab8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fail_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('lockout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lockout')
    op.drop_column('user', 'fail_count')
    # ### end Alembic commands ###
